///
/// Create by Kirito
///

namespace PiercingBlow.Login.Model.Enum
{
    public enum SendOpcode
    {
        PROTOCOL_BASE_CONNECT_ACK = 514,
        PROTOCOL_LOGIN_ACK = 259,
        PROTOCOL_BASE_GET_SYSTEM_INFO_ACK = 523,
        PROTOCOL_AUTH_GET_POINT_CASH_ACK = 1058,
        PROTOCOL_BASE_NOTICE_ACK = 662,
        PROTOCOL_BASE_GET_OPTION_ACK = 529,
        PROTOCOL_BASE_GET_USER_INFO_ACK = 525,
        PROTOCOL_BASE_GET_CHARA_INFO_ACK = 660,
        PROTOCOL_BASE_GET_CHANNELLIST_ACK = 541,
        PROTOCOL_BASE_GET_INVEN_INFO_ACK = 527,
        PROTOCOL_BASE_USER_LEAVE_ACK = 537,
        PROTOCOL_BASE_MAP_RULELIST_ACK = 669,
        PROTOCOL_BASE_MAP_MATCHINGLIST_PART_1_ACK = 671,
        PROTOCOL_BASE_MAP_MATCHINGLIST_PART_2_ACK = 671,
        PROTOCOL_BASE_MAP_MATCHINGLIST_PART_3_ACK = 671,
        PROTOCOL_BASE_URL_LIST_ACK = 672,
    }
}
