namespace PiercingBlow.Game.Model.Enum
{
    public enum RecvOpcode
    {
        PROTOCOL_ZERO = 0,
        PROTOCOL_BASE_OPTION_SAVE_REQ = 530,
        PROTOCOL_BASE_SELECT_CHANNEL_REQ = 542,
        PROTOCOL_BASE_USER_ENTER_REQ = 538,
        PROTOCOL_LOBBY_ENTER_REQ = 3073,
        PROTOCOL_LOBBY_ROOMLIST_REQ = 3077,
        PROTOCOL_LOBBY_CHATTING_REQ = 592,
        PROTOCOL_INVENTORY_ENTER_REQ = 3329,
        PROTOCOL_INVENTORY_LEAVE_REQ = 3331,
        PROTOCOL_AUTH_SHOP_ITEMLIST_REQ = 1037,
        PROTOCOL_AUTH_SHOP_GOODSLIST_REQ = 1035,
        PROTOCOL_AUTH_SHOP_REPAIRLIST_REQ = 1069,
        PROTOCOL_AUTH_SHOP_MATCHINGLIST_REQ = 1039,
        PROTOCOL_SHOP_ENTER_REQ = 1025,
        PROTOCOL_SHOP_LEAVE_REQ = 1027,
        PROTOCOL_SHOP_GET_SAILLIST_REQ = 1029,
        PROTOCOL_ROOM_CREATE_REQ = 3841,
        PROTOCOL_BASE_DAILY_RECORD_REQ = 622,
        PROTOCOL_BASE_LOGOUT_REQ = 515,
        PROTOCOL_CLAN_ENTER_REQ = 1793,
        PROTOCOL_CLAN_LEAVE_REQ = 1795,
        PROTOCOL_CLAN_LIST_REQ = 1797,
        /// <summary>
        /// Пакеты Боя.
        /// </summary>
        PROTOCOL_BATTLE_READYBATTLE_REQ = 4099,
        PROTOCOL_BATTLE_PRESTARTBATTLE_REQ = 4105,
        //После 4105 никаких пакетов сервер не требует
        PROTOCOL_BATTLE_STARTBATTLE_REQ = 4107,
        PROTOCOL_BATTLE_RESPAWN_REQ = 4113,
        PROTOCOL_BATTLE_RESPAWN_FOR_AI_REQ = 4150,
        PROTOCOL_BATTLE_DEATH_REQ = 4111,
    }
}
